
" scroll
set scrolloff=1
set scrolljump=-50
set sidescrolloff=0

set noruler
set noshowcmd
set noshowmode
set cmdheight=1



" old terminal
set guicursor=a:blinkon0-Underline
set notermguicolors


filetype off
filetype plugin off
filetype indent off
syntax off
setlocal autoindent nocindent nosmartindent indentexpr=

" imports
source ~/.vim/filetypes.vim
source ~/.vim/binds.vim
