
" прокрутка
set scrolloff=1
set scrolljump=-50
set sidescrolloff=0

set noruler
set noshowcmd
set noshowmode
set cmdheight=1



" старый терминал
set guicursor=a:blinkon0-Underline
set notermguicolors

" перенос слов
set wrap


" подсветка пробелов в конце строк
" highlight ExtraWhitespace ctermbg=9 guibg=#BF616A
" match ExtraWhitespace /\s\+$/


" типы файлов -
filetype off
filetype plugin off
filetype indent off
syntax off
setlocal autoindent nocindent nosmartindent indentexpr=

" imports
source ~/.vim/filetypes.vim
source ~/.vim/binds.vim
