unbind C-b
set -g prefix None
unbind &
unbind |
unbind -
unbind %
unbind '"'

set -g renumber-window on

# ----------------------------------------------
bind -n C-Space switch-client -T table-panes

bind -T table-panes v split-window -v -c "#{pane_current_path}"	# create vertical   pane
bind -T table-panes h split-window -h -c "#{pane_current_path}" # create horisontal pane

bind -T table-panes k kill-pane                               # kill              pane

bind -T table-panes C-f select-pane -R                          # Forward   focus pane
bind -T table-panes C-b select-pane -L                          # Backward  focus pane
bind -T table-panes C-p select-pane -U                          # Previous  focus pane
bind -T table-panes C-n select-pane -D                          # Next      focus pane

# ----------------------------------------------
bind -n M-Space switch-client -T table-windows

bind -T table-windows c new-window -c "#{pane_current_path}"       # create   window
bind -T table-windows n new-window -c "${pane_current_path}"       # create   window

bind -T table-windows k kill-window                                # kill     window
bind -T table-windows q kill-window                                # kill     window

bind -T table-windows C-n next-window                              # next     window
bind -T table-windows C-p previous-window                          # previous window

bind -T table-windows M-n next-window                              # next     window
bind -T table-windows M-p previous-window                          # previous window

# ---------------------------------------------
bind -n C-M-Space switch-client -T table-sessions

bind -T table-sessions d detach-client                        # detach session
bind -T table-sessions C-z detach-client                      # detach session
bind -T table-sessions C-q kill-session                       # kill   session

# ---------------------------------------------
set -g mouse on
set -s escape-time 0

set -g status on
set -g status-interval 1

set -g status-right "#{?client_prefix,#[fg=red]#[bold][LOCAL]#[fg=default],#{?#{==:#{prefix_current},2},#[fg=blue]#[bold][GLOBAL]#[fg=default],}}"

