# /etc/tlp.conf

TLP_ENABLE=1
RUNTIME_PM_ON_BAT=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=low
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_SCALING_MAX_FREQ_ON_AC=2100000
CPU_SCALING_MAX_FREQ_ON_BAT=1400000
PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersave
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_BAT=60
WIFI_PWR_ON_BAT=on
SOUND_QUERY_INTEL=Y
