[main]
dpi-aware=yes
font=Terminus:size=16
# font=PxPlus IBM VGA 8x16:size=16
# font=Terminus:size=26
pad=8x16

[cursor]
style=underline
blink=no
underline-thickness=2px
color={{ color_utils.alpha_off(color_utils.hex_off(theme.bg_main)) }} {{ color_utils.alpha_off(color_utils.hex_off(theme.fg_main)) }}

[colors]
background={{ color_utils.alpha_off(color_utils.hex_off(theme.bg_main)) }}
foreground={{ color_utils.alpha_off(color_utils.hex_off(theme.fg_main)) }}

selection-background={{ color_utils.alpha_off(color_utils.hex_off(theme.bg_dim)) }}
selection-foreground={{ color_utils.alpha_off(color_utils.hex_off(theme.fg_main)) }}

regular0={{ color_utils.alpha_off(color_utils.hex_off(theme.bg_dim)) }}       # black
regular1={{ color_utils.alpha_off(color_utils.hex_off(theme.red_intense)) }}   # red
regular2={{ color_utils.alpha_off(color_utils.hex_off(theme.green_intense)) }} # green
regular3={{ color_utils.alpha_off(color_utils.hex_off(theme.yellow_warmer)) }} # yellow
regular4={{ color_utils.alpha_off(color_utils.hex_off(theme.cyan_intense)) }}  # blue
regular5={{ color_utils.alpha_off(color_utils.hex_off(theme.magenta_faint)) }} # magenta
regular6={{ color_utils.alpha_off(color_utils.hex_off(theme.cyan_cooler)) }}   # cyan
regular7={{ color_utils.alpha_off(color_utils.hex_off(theme.fg_dim)) }}       # white

bright0={{ color_utils.alpha_off(color_utils.hex_off(theme.bg_alt)) }}
bright1={{ color_utils.alpha_off(color_utils.hex_off(theme.red_warmer)) }}
bright2={{ color_utils.alpha_off(color_utils.hex_off(theme.green_warmer)) }}
bright3={{ color_utils.alpha_off(color_utils.hex_off(theme.yellow_intense)) }}
bright4={{ color_utils.alpha_off(color_utils.hex_off(theme.blue_faint)) }}
bright5={{ color_utils.alpha_off(color_utils.hex_off(theme.magenta_intense)) }}
bright6={{ color_utils.alpha_off(color_utils.hex_off(theme.cyan_intense)) }}
bright7={{ color_utils.alpha_off(color_utils.hex_off(theme.fg_main)) }}
