set $main_monitor   eDP-1
set $second_monitor HDMI-A-1

output $main_monitor {
    res                     1920x1080
    pos                     760 1877
    scale                   1
    transform               0

    #max_render_time         1
}
exec waybar -c ~/.config/waybar/sway/monitor_2k/config.jsonc -s ~/.config/waybar/sway/monitor_2k/style.css
#output $main_monitor adaptive_sync on


output $second_monitor {
    res                     3840x2160
    pos                     0    0
    scale                   1.15
    transform               0

    #max_render_time         1

    bg #282828 solid_color
}
#exec waybar -c ~/.config/waybar/sway/monitor_4k/config.jsonc


#output $main_monitor {
#    res                     1920x1080
#    pos                     1420 1877
#    scale                   1
#    transform               0
#
#    #max_render_time         1
#}
## нижний правый угол
#output $second_monitor {
#    res                     3840x2160
#    pos                     0    0
#    scale                   1.15
#    transform               0
#
#    #max_render_time         1
#
#    bg #282828 solid_color
#}

# Привязка (важно: используйте кавычки для переменных)
workspace 1 output "$main_monitor"
workspace 2 output "$main_monitor"
workspace 3 output "$main_monitor"
workspace 4 output "$main_monitor"
workspace 5 output "$main_monitor"
workspace 6 output "$main_monitor"
workspace 7 output "$main_monitor"
workspace 8 output "$main_monitor"
workspace 9 output "$main_monitor"
workspace 10 output "$main_monitor"

workspace 11 output "$second_monitor"
workspace 12 output "$second_monitor"
workspace 13 output "$second_monitor"
workspace 14 output "$second_monitor"
workspace 15 output "$second_monitor"
workspace 16 output "$second_monitor"
workspace 17 output "$second_monitor"
workspace 18 output "$second_monitor"
workspace 19 output "$second_monitor"
workspace 20 output "$second_monitor"
